name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  melpa:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 27.1
          - 29.3
        ignore_warnings:
          - false
        warnings_as_errors:
          - true
        check:
          - melpa
        file:
          - elysium.el

    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - uses: leotaku/elisp-check@master
        with:
          check: ${{ matrix.check }}
          file: ${{ matrix.file }}
          ignore_warnings: ${{ matrix.ignore_warnings }}
          warnings_as_errors: ${{ matrix.warnings_as_errors }}

  ert:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 27.1
          - 29.3
        ignore_warnings:
          - false
        warnings_as_errors:
          - true
        check:
          - ert
        file:
          - test/test-elysium.el

    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - uses: leotaku/elisp-check@master
        with:
          check: ${{ matrix.check }}
          file: ${{ matrix.file }}
          ignore_warnings: ${{ matrix.ignore_warnings }}
          warnings_as_errors: ${{ matrix.warnings_as_errors }}
