name: check

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: purcell/setup-emacs@master

    - uses: leotaku/elisp-check@master
      with:
        check: melpa
        file: gptel-copilot.el
        ignore_warnings: false
        warnings_as_errors: false

    - uses: leotaku/elisp-check@master
      with:
        check: ert
        file: test/gptel-copilot-test.el
        ignore_warnings: false
        warnings_as_errors: false
